#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
cd $OPENSHIFT_DATA_DIR
rm -rf *
mkdir installation
git clone git://github.com/mde/jake.git
cd jake
make && make install PREFIX=$OPENSHIFT_DATA_DIR/installation
